Add yarp_robot_name variable in the saved mat file
robotology/yarp-telemetry pull request #162
Opened 2022-03-24 11:56 UTC by GiulioRomualdi

This closes #160

2022-03-24 13:38 UTC, Nicogene requested changes
If you tested and it work as inteded, lgtm!

Could you please add a line in the changelog and add it to a test like this one?

https://github.com/robotology/yarp-telemetry/blob/f291b7dc0d32f9d217a8a14e2eaf13ad3b3469d8/test/BufferManagerTest.cpp#L152-L182

2022-03-25 09:02 UTC, GiulioRomualdi commented
> Could you please add a line in the changelog and add it to a test like this one?
> 
> https://github.com/robotology/yarp-telemetry/blob/f291b7dc0d32f9d217a8a14e2eaf13ad3b3469d8/test/BufferManagerTest.cpp#L152-L182

Hi @Nicogene!

Changelog updated in https://github.com/robotology/yarp-telemetry/pull/162/commits/1ca0f7a32660e1f011c3c7312002d37c9107e102 

Test updated in https://github.com/robotology/yarp-telemetry/pull/162/commits/2f163fa9fa3bffb7df67d8aec03c48ccd5617fb7

2022-03-28 14:02 UTC, Nicogene approved these changes

2022-03-28 14:02 UTC, merged

2022-03-28 14:03 UTC, Nicogene commented
Merged, thanks!