Add the possibility to store channel of different types
robotology/yarp-telemetry pull request #168
Opened 2022-04-28 15:26 UTC by S-Dafarra

2022-04-28 15:35 UTC, S-Dafarra commented
This depends on the latest version of ``matio-cpp``. I just released it, but the version in ``conda`` is probably not updated yet.

2022-04-29 14:02 UTC, Nicogene requested changes
This is a very nice addition, thanks a lot @S-Dafarra!

Only some small questions, in particular about how this implementation works.

Moreover, could you please add a line in the CHANGELOG? Thanks!

2022-05-02 07:23 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/experimental/Record.h
> -    size_t m_payload{0};
It was used in some examples using directly the ``Record`` struct, but never in ``BufferManager``, which is basically the only interface used by downstream projects. In fact, when pushing to a buffer, we were passing directly the vector, and not a ``Record``. Hence, that information was not accessible anyway.

I had to remove it because it was not clear how to define the payload when using ``std::any``.

2022-05-02 07:25 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/experimental/Record.h
> +    std::any m_datum;/**< the actual data of the record */
Basically yes. Being a simple struct with two fields (having removed ``m_payload``), it is enough to use the direct-list-initialization, and a dedicated constructor was not necessary.

2022-05-02 07:32 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
> +// if T is either an Element, a Vector (but not a String), or a MultidimensionalArray
It is used here: https://github.com/robotology/yarp-telemetry/blob/0063940f1452aa0427884a9e3587f0a2b07f23c1/src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h#L138

It is used to understand how to "concatenate" the data stored for each time instant. In case of n dimensional numeric entries like scalars, vectors and multi-dimensional arrays, it is possible to concatenate in a n+1 dimensional array. On the other hand, with complex inputs like strings or structs, it is possible to concatenate only in a cell array. That struct uses SFINAE to detect if we can concatenate in a n+1 dimensional array or not.

I tried to not use SFINAE, but the problem was that I needed to check if the T::type member existed in T (being T the input type), and this was not possible using ``if constexpr``.

2022-05-02 07:36 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
> +    size_t m_dimensions_factorial{0};
It stores the result of the product of all the dimensions in ``m_dimensions``.

2022-05-02 08:21 UTC, S-Dafarra commented on src/libYARP_telemetry/src/yarp/telemetry/experimental/BufferManager.h
> +    void createMatioCppConvertFunction()
Done in https://github.com/robotology/yarp-telemetry/pull/168/commits/a53690195f8dfcabf0b53280e7cdb603ebcae5ac. Let me know if it is ok

2022-05-02 08:22 UTC, S-Dafarra commented
> Moreover, could you please add a line in the CHANGELOG? Thanks!

Done in https://github.com/robotology/yarp-telemetry/pull/168/commits/a53690195f8dfcabf0b53280e7cdb603ebcae5ac

2022-05-02 09:39 UTC, Nicogene approved these changes
Thanks for the PR and the explanations, is much more clear now!

2022-05-02 09:39 UTC, merged

2022-05-02 09:39 UTC, Nicogene commented
Merged, thanks!